# -*- coding: utf-8 -*-
"""pr2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wcYyeisKoBWiTatxOBb6tYRcbdQa4WLC
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

bankst= pd.read_csv(r"C:\Users\Prashant\Desktop\prr.csv",header=0)
bankst

bankst.head()

bankst.tail()

bankst.isnull().sum().sum()

bankst.fillna(0, inplace=True)

bankst.isnull().sum()

bankst.shape

max(bankst['Credit'])

min(bankst['Credit'])

max(bankst['Debit'])

min(bankst['Debit'])

max(bankst['Balance'])

min(bankst['Balance'])

bankst.info()

bankst.describe()

plt.figure(figsize=(35, 10))
plt.plot(bankst['Date'], bankst['Credit'])
plt.xlabel('Date')
plt.ylabel('Amount')
plt.title('Date wise Credit')
plt.show()

bankst['Date'] = bankst['Date'].tolist()

plt.figure(figsize=(50, 10))
plt.plot(bankst['Date'], bankst['Credit'])
plt.plot(bankst['Date'], bankst['Debit'])
plt.ylabel('Amount')
plt.xlabel('Date')
plt.title('Credit and Debit Transactions')
plt.legend(['Credit', 'Debit'])
plt.show()

plt.figure(figsize=(50, 10))
plt.plot(bankst['Date'], bankst['Credit'],label='Credit')
plt.ylabel('Amount')
plt.xlabel('Date')
plt.title('Credit Transactions')
plt.legend()
plt.show()

plt.figure(figsize=(50, 10))
plt.plot(bankst['Date'], bankst['Debit'],label='Debit')
plt.ylabel('Amount')
plt.xlabel('Date')
plt.title('Debit Transactions')
plt.legend()
plt.show()

plt.figure(figsize=(50, 10))
plt.plot(bankst['Date'], bankst['Balance'],label='Balance')
plt.ylabel('Amount')
plt.xlabel('Date')
plt.title('Balance Transactions')
plt.legend()
plt.show()

credittotal= bankst['Credit'].sum()

print("Total Credit is: ",credittotal)

debittotal= bankst['Debit'].sum()
print("Total Debit is: ",debittotal)

Totaldb=[debittotal,credittotal]

print(Totaldb)

totalamount=[37402.04, 37649.25]
nameamount=['Total Debit','Total Credit']
color=['red','green']
plt.figure(figsize=(40, 7))
plt.pie(totalamount, labels=nameamount, colors=color, startangle=90, explode=(0.1,0.2), shadow=True, autopct= '%1.1f%%')
plt.title('Debit and Credit')
plt.legend()
plt.show()